server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false

app:
  title: Teste spring cloud bus +
