info:
  app:
    name: config-server
    description: Servidor de configuração

server:
  port: ${PORT:8888}

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emersonlugo/spring-cloud-netflix
          searchPaths: config-repo
    bus:
     enabled: true